### ISSUE TITLE
NAT Network Internet Accessibility for nodes

### ISSUE THREAD

**Issue by stephenrlouie** [stephenrlouie/PXE-Boot-VM#1]
On a virtualbox NAT. Won't have internet access
- Fails gemini boot on pypy tar download
- Test: `wget www.google.com`, if this works, gemini will work

**Comment by danehans** [comment]
@stephenrlouie so I understand this corrrectly, using a vbox nat network does not allow the gem managed nodes to hit the Internet?

**Comment by stephenrlouie** [comment]
It doesn't always allow the gem managed nodes to hit the internet. I cannot find where or why some machines cannot `wget www.google.com`. 

The interface comes up and gets an IP. Its odd because they can often resolve the domain name to an IP, just not connect to the server.

I tried a bridged adapter but that did not seem to fix anything either.

**Comment by danehans** [comment]
OK. I think this is the highest priority fix for all the vagrant stuff you've been doing. Try leveraging community resources for support if you get nowhere in the next day.

**Comment by stephenrlouie** [comment]
Was setting a default route on the internal network and the NAT. Updated the dhcpd.conf to not provide an option-router, now the NAT is the only default route. 

[Commit](https://github.com/stephenrlouie/PXE-Boot-VM/commit/55586aa69fa0bb6878abd47564a99b4fe699baa4)
